### ISSUE TITLE
Resize Ui, shorten list width

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#100]
The list width is too long, and more space needs to be given to the command output/remarks area

![image](https://user-images.githubusercontent.com/35413456/228194067-2fb8899f-8454-4718-801c-8c5ed82734d7.png)

It's more apparent when u shorten the app width:

![image](https://user-images.githubusercontent.com/35413456/228194345-c93b4d43-1ee6-4dae-9a7a-73b94ddd1ef0.png)

**Comment by wendy0107** [comment]
![image](https://user-images.githubusercontent.com/79928462/228676470-0178fca7-d129-4006-9e8b-e4d635e7fa8f.png)

you can drag the slider in the middle to resize the window :D no need to resize unless we want to adjust the default window size when the app is first launched
