### ISSUE TITLE
Add confirmation for clear feat.

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#117]
Currently, we just type `clear` and poof our entries all gone. We also have no undo comamnd atm, so yea.

A design flaw, WHICH NEEDS TO BE DONE IN 1.3

But a popup confirmation might break the "CLI only" experience. Though its also arguable that u don't often clear all ur entries so its not a common occurance.

some suggestions:
- popup yes/no
- require a 2nd yes/no command, like in bash
- require typing something as a argument for the clear, like GitHub "if ure sure u want to delete this repo, type in the repo name"
  (eg. like the number of listed students, or the first student's name)

**Comment by wendy0107** [comment]
We implemented undo and redo so this is fine now :)
