### ISSUE TITLE
Delete valid duplicate indexes doesn't clear command line

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#132]
Yet it deletes the person correctly. I think it deletes the person, then runs into an error and dies

## Before entering command
![image](https://user-images.githubusercontent.com/35413456/228887850-ac527645-a9f2-4c29-8738-f46dbc0466cc.png)

## After entering command
![image](https://user-images.githubusercontent.com/35413456/228888135-1574c948-5676-4abf-beda-01b0b8ce4c70.png)

**Comment by Bentimate** [comment]
#266
