### ISSUE TITLE
[PE-D][Tester D] This Features hyperlink does not redirect the user to the right section in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W12-2/tp#164]
![image.png](https://raw.githubusercontent.com/igezt/ped/main/files/3303ce99-a14f-4ce6-8cd3-ecdb15ca5438.png)

This can be confusing for the user because they are unable to know if there is a Features section or not.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: igezt/ped#3

**Comment by wendy0107** [comment]
Invalid
