### ISSUE TITLE
[PE-D][Tester A] Delete 0 command 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W12-2/tp#166]
![Screenshot 2023-03-31 at 2.22.56 PM.png](https://raw.githubusercontent.com/Diatbbin/ped/main/files/8227f67d-d340-4562-9d65-30a330e97340.png)

Nothing changes when I try delete 0. There should be an error message for it.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Diatbbin/ped#3

**Comment by Bentimate** [comment]
#159
