### ISSUE TITLE
Improve autosave feature

### ISSUE THREAD

**Issue by Bentimate** [AY2223S2-CS2103T-W12-2/tp#17]
As a new user, I should have the changes I made to my entries be saved automatically, so that I would not lose any changes when I close and reopen the program.

**Comment by EvitanRelta** [comment]
# Current `AB3` autosave feat.
`AB3` already autosaves any new/edited person's info. So this feat. is pretty much done.

# Suggested improvements

The only things that we could expand on this is the things below. **But both of them is low-priority / not important**

- autosave currently entered command 
  *(eg. User enters `add n/PARTIAL_ENTERED_NAME` and exits the app. Next time the app opens, it will fill in that partial command)*

- autosave last command's output
  *(eg. User does `find Alex`, app shows only `Alex Goh`, user exits app. Next time the app opens, it will still only show `Alex Goh`, like how it was left off)*
