### ISSUE TITLE
Improve `find` command

### ISSUE THREAD

**Issue by Bentimate** [AY2223S2-CS2103T-W12-2/tp#18]
As a user with some experience, I can find for a specific student based on some keyword, so that I can quickly find and view or make changes to his information.

**Comment by EvitanRelta** [comment]
# Limitations
Currently, `AB3` already have a find feature, although with some limitations:
- can only find words within the person's name 
  *(ie. u can't filter via tags, address or phone)*

- can only search whole words 
  *(eg. `find ale` will not return person `Alex Goh`. u need to enter `find alex`)*

- keywords are forced to be logically-OR with each other 
  *(ie. `find alex goh` returns `Alex Goh` and `Calvin Goh`)*

# Suggested plan
- implement ability to find/filter by tags/user-info
  *(eg. `address:choa chu subject:math` or `a/choa chu s/math`)*

- allow partial-word matches
    *(eg. `find ale` returns `Alex Goh`)*
