### ISSUE TITLE
[PE-D][Tester C] Filter images not loading properly on windows

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W12-2/tp#193]
![image.png](https://raw.githubusercontent.com/alson001/ped/main/files/860acde1-b0e3-434e-9b54-7b2b31a07a0b.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: alson001/ped#8

**Comment by wendy0107** [comment]
Documentation bug, fixed in 1.4
