### ISSUE TITLE
Autocomplete not updated with new tags

### ISSUE THREAD

**Issue by Bentimate** [AY2223S2-CS2103T-W12-2/tp#241]
Autocomplete does not seem to be updated immediately when I add/edit a new tag, but will only be updated after restart.

tested from a fresh copy of the 1.3.5 release
(if this is intended please ignore and close)
![own](https://user-images.githubusercontent.com/81696093/229939874-095c1518-1c08-4924-bb0e-5162c1ed91ca.JPG)

**Comment by wendy0107** [comment]
I think fix alr 
![image](https://user-images.githubusercontent.com/79928462/230055192-13214581-f0be-427e-b604-150ee03df341.png)

newtags and dumb were edited and added in respectively and the autocomplete is updated with them
