### ISSUE TITLE
Find/Filter section in DG needs updating

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#289]
# Find section bugs
## The predicate name was changed right?
![image](https://user-images.githubusercontent.com/35413456/230754914-c583706f-4864-4185-af4b-3d9cd03f830c.png)
![image](https://user-images.githubusercontent.com/35413456/230754931-0bfb4a97-376a-4a4d-856f-c2d4099abbb6.png)

## Kinda incorrect format? since it must search in a prefix.
![image](https://user-images.githubusercontent.com/35413456/230754997-41bcbbbe-9385-4990-b0d0-97926abb50e0.png)

## Im not sure if using `PARTIAL_KEYWORD` is ok? or should it just be normal text "partial keyword"

![image](https://user-images.githubusercontent.com/35413456/230755079-b898221b-37c9-472a-96a3-60f92fff6f27.png)

# Filter section bugs
## Didn't mention the predicate class like in find
![image](https://user-images.githubusercontent.com/35413456/230755170-5e0a84e8-5223-4313-948b-bf8f3587b243.png)

## Typos
![image](https://user-images.githubusercontent.com/35413456/230755227-a7b310a0-6e5a-4d56-897d-9a276efcb471.png)

## Not updated sub sections
![image](https://user-images.githubusercontent.com/35413456/230754876-f64c0e18-1acc-41f0-8f91-d00358b9e99a.png)

# Potentially more things to add
- allowing multiple of the same prefix `find n/Person1 n/Person2`

**Comment by Bentimate** [comment]
Left the find /filter UML diagram
