### ISSUE TITLE
Remarks - Implement `showremark` command to show hidden student-remarks

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#44]
As a new user, I can check a specific student's remarks without it bloating the students list, so that I can see extra information pertaining to that student without having a long bloated students list.

> Smaller story of #16 

The plan is for each student entry to have a student-specific notes called "remarks", which is hidden in the student list to avoid clutering the list with long notes.

`showremark [INDEX]` will be the command to display a student's remarks.

For `v1.2`, this will display the remarks in the command output/error textbox.  
But in future, it will be displayed in a textbox on the left as shown in our mockup:

![image](https://user-images.githubusercontent.com/35413456/224940010-19b95423-6d99-4092-b4fa-38db2f6e275c.png)

**Comment by Bentimate** [comment]
v1. Added a `show` command to show an entry's remarks by index
