### ISSUE TITLE
`edit [INDEX] edu/` doesn't remove education tag

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#72]
When `edit 1 edu/` is entered:

![image](https://user-images.githubusercontent.com/35413456/226867292-ec483933-2499-40fb-a3fd-8edf42cd1e4c.png)

It adds an empty education tag instead of removing the education tag:

![image](https://user-images.githubusercontent.com/35413456/226867361-0ea5e0cb-c409-4ecc-b5fe-dea45c61a0e8.png)

**Comment by Bentimate** [comment]
addressed in #174
