### ISSUE TITLE
Rename released `jar` file from `addressbook.jar` to `teachmesenpai.jar`

### ISSUE THREAD

**Issue by EvitanRelta** [AY2223S2-CS2103T-W12-2/tp#86]
The `jar` file name in the GitHub release page is still `addressbook.jar`.  
It should be changed to `teachmesenpai.jar`.

![image](https://user-images.githubusercontent.com/35413456/227764906-c8ff3e5b-c316-4b77-a648-b7508a94be04.png)

**Comment by Zxun2** [comment]
nice name
